### PR TITLE
Switch from coroutine-rs to context-rs.

### LINKED ISSUE #6: Evaluate using coroutine::Context instead of coroutine::Coroutine. Maybe there are some gains by not using global scheduling etc.
Mioco requires only a context switch from and from each handler, and does not require full flexible model of `coroutine` with keeping track of runnable coroutines etc.

Right now mioco uses coroutine primitives, potentially that are shared with other users of `coroutine`. If any handler was to use call `Coroutine::yield()` or other control mechanisms on it's own, that could lead to rather unexpected results within mio.

That's another reason, to plug into lower-level coroutine::Context interface.

### PR DESCRIPTION
**Pull request by dpc**
Fix #6

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -358,15 +450,10 @@ impl Coroutine {
     fn after_resume(&mut self, event_loop: &mut EventLoop<Handler>) {
         // If there were any newly spawned child-coroutines: start them now
         for coroutine in &self.children_to_start {
-            let handle = {
-                let co = coroutine.borrow_mut();
-                co.handle.as_ref().map(|c| c.clone()).unwrap()
-            };
             trace!("Resume new child coroutine");
             {
```
Comment (dpc) [inline src/lib.rs]: Needless.

File: src/lib.rs [hunk 2]
```diff
@@ -569,9 +702,10 @@ where T : Reflect+'static {
             inn.coroutine.borrow_mut().state = State::BlockedOn(rw);
             inn.coroutine.borrow_mut().blocked_on.clear_all();
             inn.coroutine.borrow_mut().blocked_on.set(inn.id, true);
-        }
+        };
         trace!("coroutine blocked on {:?}", rw);
-        coroutine::Coroutine::block();
+        let coroutine_ref = {self.inn.borrow().coroutine.clone() };
```
Comment (dpc) [inline src/lib.rs]: Needless { } ?
